### ISSUE TITLE
AttributeError: _member_count

### ISSUE THREAD

**Issue by NateSteelHD** [Leastrio/discord-welcome#1]
when member join it shows this error, i already search for it but nothing is fix still the same, can you help me out xd
### Ignoring exception in on_member_join
```
Traceback (most recent call last):
  File "C:\Users\Nates\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Nates\Desktop\discord-welcome\main.py", line 35, in on_member_join
    draw.text((160, 80),f"You are the {guild.member_count}th member",(255,255,255),font=font)
  File "C:\Users\Nates\AppData\Local\Programs\Python\Python38-32\lib\site-packages\discord\guild.py", line 717, in member_count
    return self._member_count
AttributeError: _member_count
```

**Comment by 1THGAMER1** [comment]
I have the same problem

**Comment by Leastrio** [comment]
Ill try to look into this soon :)

**Comment by Leastrio** [comment]
Just fixed it!
